---
- name: Create directory for AppDynamics Machine Agent
  file:
    path: /opt/appdynamics/machineagent
    state: directory
    owner: eis
    group: eis
    mode: '0755'
  become: yes

- name: Unzip AppDynamics Machine Agent
  unarchive:
    src: "{{ playbook_dir }}/files/appdynamics-machine-agent.zip"
    dest: /opt/appdynamics/machineagent
    remote_src: yes
  become: yes

- name: Generate Machine Agent configuration
  template:
    src: machine-agent.yml.j2
    dest: /opt/appdynamics/machineagent/conf/machine-agent.yml
  vars:
    controller_host: "your-controller-host"
    controller_port: 8090
    account_name: "your-account-name"
    account_access_key: "your-account-access-key"
    application_name: "your-application-name"
    tier_name: "your-tier-name"
  become: yes

- name: Create systemd service file
  template:
    src: appdynamics-machine-agent.service.j2
    dest: /etc/systemd/system/appdynamics-machine-agent.service
  become: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start the AppDynamics Machine Agent service
  systemd:
    name: appdynamics-machine-agent
    enabled: yes
    state: started
  become: yes
