---
- name: Perform tasks based on third octet of IP address
  hosts: localhost
  gather_facts: yes

  vars:
    packages_based_on_third_octet:
      10: "package1"
      20: "package2"
      30: "package3"
    variable_values_based_on_third_octet:
      10: "value1"
      20: "value2"
      30: "value3"
    third_octet: "{{ ansible_default_ipv4.address.split('.')[2] }}"
    package_to_install: "{{ packages_based_on_third_octet[third_octet|int] }}"
    variable_value: "{{ variable_values_based_on_third_octet[third_octet|int] }}"

  tasks:
    - name: Debug variables
      debug:
        msg: "Third octet: {{ third_octet }}, Package to install: {{ package_to_install }}, Variable value: {{ variable_value }}"

    - name: Install package based on third octet
      yum:
        name: "{{ package_to_install }}"
      when: package_to_install is defined

    - name: Debug tasks
      debug:
        msg: "Perform tasks for IP {{ ansible_default_ipv4.address }} with third octet {{ third_octet }}, variable value {{ variable_value }}, and installed package"
      when: third_octet|int in packages_based_on_third_octet.keys()
