---
- name: Create sudoers.d file
  hosts: your_target_servers
  become: yes

  vars:
    sudoers_file_content: |
      # Example sudoers.d file
      # Replace 'your_username' with the desired username and add the necessary configurations.
      your_username ALL=(ALL) NOPASSWD: /bin/your_command

  tasks:
    - name: Copy sudoers.d file
      copy:
        content: "{{ sudoers_file_content }}"
        dest: /etc/sudoers.d/your_filename  # Change 'your_filename' to the desired filename
        mode: '0440'
      validate: 'visudo -c -f %s'
