---
- name: Get SELinux state
  command: "/sbin/getenforce"
  register: selinux_state
  tags:
  - configuration
  - selinux

- name: Modify SELinux
  selinux:
    conf: "{{ item.value.config | d(omit) }}"
    policy: "{{ item.value.policy | d(omit) }}"
    state: "{{ item.value.state | d(disabled) }}"
  with_dict: "{{ selinux }}"
  tags:
  - configuration
  - selinux

- name: Modify SELinux current state
  command: "/usr/sbin/setenforce {{ item }}"
  with_items:
  - "{{ (selinux.global.state != 'enforcing') | ternary('0','1') }}"
  when: '"Disabled" not in selinux_state.stdout'
  tags:
  - configuration
  - selinux
