---
- name: Check Ansible version
  assert:
    that: "ansible_version.full is version_compare('2.5', '>=')"
    msg: "You must update Ansible to at least 2.5 to use this role"
  tags:
  - check
  - always

- name: Check OS
  fail:
    msg: 'The operating system of the target machine "{{ inventory_hostname }}" is
      not currently supported.'
  when: ansible_os_family not in ['RedHat']
  tags:
  - check
  - always
