---
- name: Create sudoers file for user eis
  become: yes

  tasks:
    - name: Create sudoers file
      blockinfile:
        path: /etc/sudoers.d/eis
        block: |
          # Sudoers file for user eis
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start dxp.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status dxp.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop dxp.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart dxp.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start tomcat.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status tomcat.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop tomcat.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart tomcat.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start solr.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status solr.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop solr.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart solr.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start zookeeper.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status zookeeper.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop zookeeper.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart zookeeper.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start nessusagent.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status nessusagent.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop nessusagent.service
          eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart nessusagent.service
          eis             ALL=(ALL)       NOPASSWD: /bin/rpm       query installed rpm to make java home dynamic
      notify: 
        - Restart sudo service
          
  handlers:
    - name: Restart sudo service
      service:
        name: sudo
        state: restarted
