---
- name: Install required packages
  apt:
    name: [openjdk-11-jdk, unzip]
    state: present
  become: yes

- name: Create Tomcat installation directory
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Download and extract Tomcat
  get_url:
    url: "https://downloads.apache.org/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}/tomcat-{{ tomcat_version }}.tar.gz"
  become: yes

- name: Extract Tomcat archive
  unarchive:
    src: "{{ tomcat_install_dir }}/tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes
  become: yes

- name: Create symbolic link for Tomcat
  file:
    src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ tomcat_install_dir }}/tomcat"
    state: link
    force: yes
  become: yes

- name: Copy Tomcat systemd service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  become: yes

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    enabled: yes
    state: started
  become: yes
