# handlers/main.yml
---
- name: restart redis
  service:
    name: redis
    state: restarted
- name: restart sentinel
  service:
    name: redis-sentinel
    state: restarted
- name: Restart firewalld
  service:
    name: firewalld
    state: restarted		