---
- name: Create sudoers.d file
  become: yes

  vars:
    sudoers_file_content: |
      # Example sudoers.d file
      # Replace 'your_username' with the desired username and add the necessary configurations.
      your_username ALL=(ALL) NOPASSWD: /bin/your_command
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start dxp.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status dxp.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop dxp.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart dxp.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start tomcat.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status tomcat.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop tomcat.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart tomcat.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start solr.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status solr.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop solr.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart solr.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start zookeeper.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status zookeeper.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop zookeeper.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart zookeeper.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl start nessusagent.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl status nessusagent.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl stop nessusagent.service
      eis             ALL=(ALL)       NOPASSWD: /bin/systemctl restart nessusagent.service
      eis             ALL=(ALL)       NOPASSWD: /bin/rpm       query installed rpm to make java home dynamic

  tasks:
    - name: create sudoers.d file
      copy:
        content: "{{ sudoers_file_content }}"
        dest: /etc/sudoers.d/eissudoers  # Change 'your_filename' to the desired filename
        mode: '0440'
      validate: 'visudo -c -f %s'
