---
- name: Create backup of SELinux configuration
  command: cp -p /etc/selinux/config /etc/selinux/config.bak
  changed_when: false
  ignore_errors: true

- name: Disabling SELinux state
  ansible.posix.selinux:
    state: disabled