---
- name: Check the amount of memory
  ansible.builtin.setup:
  register: memory_info

- name: Calculate swap size
  set_fact:
    swap_size_mb: "{{ (memory_info.ansible_facts['ansible_memory_mb']['real'] * 0.25) | round | int }}"

- name: Configure swap based on memory
  include_tasks: "{{ ansible_distribution | lower }}.yml"
