---
- name: Get total memory size
  shell: "grep MemTotal /proc/meminfo | awk '{print $2}'"
  changed_when: false
  register: total_memory

- name: Calculate swap size and swappiness
  set_fact:
    swap_size: "{{ (total_memory.stdout|int) / 1024 * 2 }}"  # Adjust the multiplier as needed
    swappiness: "{{ '10' if total_memory.stdout|int > 819200 else '60' }}"  # Adjust the threshold as needed

- name: Create swap file
  command: "dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size }}"

- name: Set permissions on swap file
  command: "chmod 600 /swapfile"

- name: Set up swap space
  command: "mkswap /swapfile"

- name: Enable swap
  command: "swapon /swapfile"

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    state: present

