---
- name: Configure swap on Red Hat/CentOS
  ansible.builtin.command: "dd if=/dev/zero of=/swapfile count={{ swap_size_mb }} bs=1M"
  become: yes

- name: Set permissions on the swapfile
  ansible.builtin.file:
    path: /swapfile
    mode: '0600'
  become: yes

- name: Create swap area
  ansible.builtin.command: "mkswap /swapfile"
  become: yes

- name: Configure swap settings in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: '/swapfile swap swap defaults 0 0'
    regexp: '^/swapfile'
  become: yes
  notify: Activate swap

handlers:
  - name: Activate swap
    ansible.builtin.command: "swapon -a"
    become: yes
