---
- name: Manage public ports with firewalld ansible module 
  hosts: 51.254.39.241
  gather_facts: no
  become: true
vars:
    port_list:
      - { port: 8181/tcp, state: enabled }
      - { port: 9191/tcp, state: disabled }
      - { port: 5050/udp, state: enabled }
tasks:
    - name: Enable ports on the list
      firewalld:
        zone: public
        port: "{{ item.port }}"
        permanent: true
        state: "{{ item.state }}"
      loop:
        "{{ port_list }}"
      notify:
        - Restart firewalld
handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted		