---
- name: Install AWS CLI dependencies if not already installed
  apt:
    name:
      - unzip
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install AWS CLI dependencies if not already installed
  yum:
    name:
      - unzip
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Download the awscli bundle.
  get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=/tmp/awscli-bundle.zip
  register: aws_cli_download_bundle

- name: Unarchive the installer.
  unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no creates=/tmp/aws list_files=true
  when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer

- name: Install awscli package.
  shell: python /tmp/awscli-bundle/install -i --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli
  args:
    creates: /usr/local/aws-cli
  when: aws_cli_unarchive_installer.changed

- name: Creating the file to add aws to the path
  file:
    path: "/etc/profile.d/aws.sh"
    state: touch
    mode: 0644
    owner: root

- name: Set environment variables for Aws Cli (for Debian-based systems)
  become: true
  become_user: root
  lineinfile:
    dest: /etc/environment
    line: 'AWS_HOME="/usr/local/bin"'
    state: present
  when: ansible_os_family == 'Debian'

- name: Set environment variables for Aws Cli (for RedHat-based systems)
  become: true
  become_user: root
  lineinfile:
    dest: /etc/profile.d/aws.sh
    line: 'export AWS_HOME="/usr/local/bin"'
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add Aws Cli executable to PATH (for Debian-based systems)
  become: true
  become_user: root
  lineinfile:
    dest: /etc/environment
    line: 'PATH="$PATH:$AWS_HOME"'
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Aws Cli executable to PATH (for RedHat-based systems)
  become: true
  become_user: root
  lineinfile:
    dest: /etc/profile.d/aws.sh
    line: 'export PATH="$PATH:$AWS_HOME"'
    state: present
  when: ansible_os_family == 'RedHat'
