---
- name: Check if AWS CLI v2 is installed
  command: aws --version
  register: aws_cli_installed
  ignore_errors: true

- name: Download AWS CLI v2 installer
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscli-exe-linux-x86_64.zip
  when: aws_cli_installed.rc != 0

- name: Unzip AWS CLI v2 installer
  ansible.builtin.unarchive:
    src: /tmp/awscli-exe-linux-x86_64.zip
    dest: /tmp/aws-cli
    remote_src: yes
  when: aws_cli_installed.rc != 0

- name: Install AWS CLI v2
  ansible.builtin.command: /tmp/aws-cli/aws/install
  args:
    creates: /usr/local/bin/aws
  when: aws_cli_installed.rc != 0

- name: Add AWS CLI v2 to PATH using profile.d
  ansible.builtin.copy:
    content: "export PATH=$PATH:/usr/local/bin/aws"
    dest: /etc/profile.d/awscli.sh
    mode: '0755'
    owner: root
    group: root
  notify: Update shell environment

handlers:
  - name: Update shell environment
    ansible.builtin.command: "bash /etc/profile.d/awscli.sh"
