---
- name: Install Apache Solr and Create Service File with Symbolic Links
  hosts: your_target_servers
  become: yes

  vars:
    solr_version: "9.0.0"   # Change this to the desired Solr version
    solr_user: "solr"
    solr_group: "solr"
    solr_install_dir: "/opt/solr"
    solr_data_dir: "/var/solr/data"
    solr_home_link: "/opt/solr-latest"  # Change this to the desired symlink location
    java_package: "openjdk-11-jdk"  # Change this based on your desired Java package

  tasks:
    - name: Create Solr user
      user:
        name: "{{ solr_user }}"
        home: "{{ solr_install_dir }}"
        shell: "/bin/bash"
        system: yes
        state: present

    - name: Install required packages (for Debian/Ubuntu-based systems)
      apt:
        name:
          - {{ java_package }}
          - unzip
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install required packages (for RedHat/CentOS-based systems)
      yum:
        name:
          - java-11-openjdk-devel  # Change this based on your desired Java package for RedHat/CentOS
          - unzip
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Download Solr
      get_url:
        url: "https://downloads.apache.org/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "/tmp/solr.tar.gz"

    - name: Extract Solr
      unarchive:
        src: "/tmp/solr.tar.gz"
        dest: "{{ solr_install_dir }}"
        remote_src: yes
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"

    - name: Set Solr permissions
      file:
        path: "{{ solr_install_dir }}"
        state: directory
        recurse: yes
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: "0755"

    - name: Create a symlink to the Solr installation
      file:
        src: "{{ solr_install_dir }}"
        dest: "{{ solr_home_link }}"
        state: link
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"

    - name: Configure Solr data directory
      file:
        path: "{{ solr_data_dir }}"
        state: directory
        owner: "{{ solr_user }}"
        group: "{{ solr_group }}"
        mode: "0755"

    - name: Create Solr service file
      template:
        src: solr.service.j2
        dest: "/etc/systemd/system/solr.service"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Reload systemd manager configuration
      systemd:
        daemon_reload: yes

    - name: Start Solr service and enable it on boot
      service:
        name: solr
        state: started
        enabled: yes
