---
- name: Update packages on Debian/Ubuntu
  when: ansible_distribution in ['Debian', 'Ubuntu']
  apt:
    upgrade: 'safe'

- name: Update packages on Red Hat/CentOS
  when: ansible_distribution in ['RedHat', 'CentOS']
  yum:
    name: '*'
    state: latest

- name: Update packages on Fedora
  when: ansible_distribution == 'Fedora'
  dnf:
    name: '*'
    state: latest

- name: Update packages on SUSE
  when: ansible_distribution == 'SUSE'
  zypper:
    name: '*'
    state: latest

