---
- name: Configure Chrony with AWS Best Practices
    - name: Install Chrony package
      package:
        name: chrony
        state: present

    - name: Copy Chrony configuration file
      template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
      notify: Restart Chrony

  handlers:
    - name: Restart Chrony
      systemd:
        name: chronyd
        state: restarted
