---
galaxy_info:
  description: Create and manage environment (users, groups, system limits)
  company: EIS Group
  license: GPLv2
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
    - 6
  - name: Amazon
    versions:
    - all
  categories:
  - system
allow_duplicates: false
dependencies: []
