---
- name: Create ZooKeeper home directory
  file:
    path: "/opt/zookeeper/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Create ZooKeeper version directory
  file:
    path: "/opt/zookeeper/versions"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Create ZooKeeper data directory
  file:
    path: "/opt/zookeeper/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Create ZooKeeper conf directory
  file:
    path: "/opt/zookeeper/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Download the ZooKeeper archive
  get_url:
    url: "https://downloads.apache.org/zookeeper/zookeeper-3.6.3/apache-zookeeper-3.6.3-bin.tar.gz"
    dest: "/tmp"
  become: yes

- name: Unarchive ZooKeeper
  unarchive:
    src: "/tmp/apache-zookeeper-3.6.3-bin.tar.gz"
    dest: "/opt/zookeeper/versions"
    remote_src: yes
  become: yes

- name: Set symbolic link to latest ZooKeeper installation
  file:
    src: "/opt/zookeeper/versions/apache-zookeeper-3.6.3-bin"
    dest: "/opt/zookeeper/latest"
    state: link
    force: yes
  become: yes

- name: Create ZooKeeper configuration file
  template:
    src: zoo.cfg.j2
    dest: "/opt/zookeeper/conf/zoo.cfg"
  become: yes

- name: Create ZooKeeper systemd service file
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  become: yes

- name: Set permissions for ZooKeeper service file
  file:
    path: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes
