---
- name: Include generic variables used by all systems
  include_vars: common.yml

- name: Include OS-specific variables for Fedora or FreeBSD.
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'FreeBSD' or ansible_distribution == 'Fedora'

- name: Include version-specific variables for CentOS/RHEL.
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: >-
    ansible_distribution in [
      'CentOS',
      'Red Hat Enterprise Linux',
      'RedHat',
      'Rocky',
      'AlmaLinux'
    ]

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Include version-specific variables for Debian.
  include_vars: "{{ ansible_distribution | title }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

# Setup/install tasks.
- include_tasks: setup-RedHat7.yml
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7")

- include_tasks: setup-RedHat8.yml
  when: (ansible_os_family == 'RedHat' and ansible_distribution_major_version == "8")

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Debian.yml
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7")

- include_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- include_tasks: setup-amazon.yml
  when: (ansible_distribution == "amazon" and ansible_distribution_major_version == "7")
